"""add new warning to detect text manipulation

Revision ID: 413a23091c12
Revises: 89e64b4e7c7f
Create Date: 2024-08-09 17:49:59.658146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413a23091c12'
down_revision: Union[str, None] = '89e64b4e7c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'big_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('big_id', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
