"""Add daily forecast table

Revision ID: 68780b269846
Revises: e77ce708d560
Create Date: 2024-05-04 22:32:45.928529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68780b269846'
down_revision: Union[str, None] = 'e77ce708d560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_forecasts_created_at'), 'daily_forecasts', ['created_at'], unique=False)
    op.alter_column('users', 'daily_forecast',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'daily_forecast',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_daily_forecasts_created_at'), table_name='daily_forecasts')
    op.drop_table('daily_forecasts')
    # ### end Alembic commands ###
