"""Add warning table

Revision ID: 9b634e65476d
Revises: cec1920b7871
Create Date: 2024-08-07 22:13:02.318111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b634e65476d"
down_revision: Union[str, None] = "cec1920b7871"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "warnings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "warning",
            sa.Enum(
                "hacking_attempt",
                "inappropriate_behavior",
                "repetitive_unrelated_input",
                "inappropriate_language",
                name="warningtype",
            ),
            nullable=False,
        ),
        sa.Column("warning_explanation", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_warnings_timestamp"), "warnings", ["timestamp"], unique=False
    )
    op.drop_column("users", "target_topics")
    op.drop_column("users", "hobbies")
    op.drop_column("users", "self_description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("self_description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users", sa.Column("hobbies", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("target_topics", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_warnings_timestamp"), table_name="warnings")
    op.drop_table("warnings")
    # ### end Alembic commands ###
