"""Add advices table

Revision ID: cec1920b7871
Revises: 1b11d7c10f00
Create Date: 2024-08-07 20:24:28.378370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cec1920b7871"
down_revision: Union[str, None] = "1b11d7c10f00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "advices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("situation", sa.Text(), nullable=False),
        sa.Column("advice", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_advices_timestamp"), "advices", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_advices_timestamp"), table_name="advices")
    op.drop_table("advices")
    # ### end Alembic commands ###
