"""Create a baseline migrations

Revision ID: e359709de284
Revises: 
Create Date: 2024-04-20 16:59:45.782557

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e359709de284"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("date_of_birth_text", sa.String(length=60), nullable=True),
        sa.Column(
            "language",
            sa.Enum(
                "English",
                "Arabic",
                "Chinese",
                "French",
                "German",
                "Italian",
                "Japanese",
                "Korean",
                "Portuguese",
                "Russian",
                "Spanish",
                "Ukrainian",
                name="language",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
