"""Add subscription flag

Revision ID: e77ce708d560
Revises: e359709de284
Create Date: 2024-05-02 20:28:56.627064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e77ce708d560'
down_revision: Union[str, None] = 'e359709de284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_forecast', sa.Boolean(), nullable=True))
    op.drop_column('users', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', postgresql.ENUM('English', 'Arabic', 'Chinese', 'French', 'German', 'Italian', 'Japanese', 'Korean', 'Portuguese', 'Russian', 'Spanish', 'Ukrainian', name='language'), autoincrement=False, nullable=True))
    op.drop_column('users', 'daily_forecast')
    # ### end Alembic commands ###
