"""Add jokes table

Revision ID: edaaa7e0d86b
Revises: 9b634e65476d
Create Date: 2024-08-07 23:04:31.563236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edaaa7e0d86b'
down_revision: Union[str, None] = '9b634e65476d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jokes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('astrologic_joke', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jokes_timestamp'), 'jokes', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jokes_timestamp'), table_name='jokes')
    op.drop_table('jokes')
    # ### end Alembic commands ###
